/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Quick Restore",
  "description": "After reloading the page, you can choose to restore a project from the cache.",
  "tags": [
    "new"
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "enabledByDefault": false
};
export default manifest;
