/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "enabledByDefault": false,
  "name": "SVG Security Sandbox (Deprecated)",
  "description": "DEPRECATED: SVG security features have been integrated into the core upload pipeline. This addon is no longer needed and has been disabled.",
  "credits": [
    {
      "name": "Thomas Weber",
      "link": "https://github.com/GarboMuffin"
    }
  ],
  "tags": ["security", "deprecated"],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
